import rtconfig
from building import *

cwd     = GetCurrentDir()
path = [cwd, str(Dir('#'))]
src = Split('''
main.c
protocol/mem_list.c
driver/crc.c
driver/icm42688.c
driver/icm20603.c
''')

path += [cwd + '/protocol']
path += [cwd + '/driver']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
