Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'applications')

src = Split("""
application.c
startup.c
subPoint.c
readwrite.c
master.c
m26.c
nbiot.c
ec20.c
pcie.c
wtn6.c
prop.c
listdir.c
can.c
traditional_alarm.c
""")

if GetDepend('RT_USING_CAN'):
    src += ['canapp.c']

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
