Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'applications')

src = Split("""
application.c
startup.c
subPoint.c
readwrite.c
master.c
m26.c
nbiot.c
ec20.c
pcie.c
wtn6.c
prop.c
listdir.c
can.c
traditional_alarm.c
w5500/w5500.c
w5500/socket.c
w5500/ftpc.c
w5500/dhcp.c
w5500/wizchip_conf.c
w5500/ip.c
w5500/dns.c
""")

if GetDepend('RT_USING_CAN'):
    src += ['canapp.c']

CPPPATH = [cwd, str(Dir('#'))]
CPPPATH += [cwd + '/w5500']
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
