import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
w25qxx.c
md5.c
""")

path = [cwd]
group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
